#@ load("@ytt:data", "data")
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: deployment-metrics.tanzu.vmware.1.0.0
spec:
  refName: deployment-metrics.tanzu.vmware
  version: #@ data.values.version
  releaseNotes: |
        Initial release of the deployment metrics package
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: #@ data.values.package_reference
      template:
      - ytt:
          paths:
          - "keptn/"
          - "jaegar/"
          - "grafana/"
      - kbld:
          paths:
          - ".imgpkg/images.yml"
          - "-"
      deploy:
      - kapp: {}