---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: deployment-metrics.tanzu.vmware.1.0.0
spec:
  refName: deployment-metrics.tanzu.vmware
  version: 1.0.0
  releaseNotes: |
        Initial release of the deployment metrics package
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.build.h2o-2-18171.h2o.vmware.com/metrics/deployment-metrics:1.0.4
      template:
      - ytt:
          paths:
          - "keptn/"
          - "jaegar/"
          - "grafana/"
      - kbld:
          paths:
          - ".imgpkg/images.yml"
          - "-"
      deploy:
      - kapp: {}