---
apiVersion: options.keptn.sh/v1alpha1
kind: KeptnConfig
metadata:
  name: keptnconfig-sample
  namespace: lifecycle-metrics
spec:
  OTelCollectorUrl: 'jaeger-collector.lifecycle-metrics.svc.cluster.local:4317'
  keptnAppCreationRequestTimeoutSeconds: 30
