---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-ns-sa
  namespace: tkg-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-ns-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-ns-role-binding
subjects:
- kind: ServiceAccount
  name: default-ns-sa
  namespace: tkg-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: default-ns-role
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: deployment-metrics-package-repo
  namespace: tkg-system
spec:
  fetch:
    imgpkgBundle:
      image: harbor.build.h2o-2-18171.h2o.vmware.com/library/metrics:72636ad71f8ad8e1aceb9c82677bff6745deb847
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: metrics
  namespace: tkg-system
  annotations:
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: jaegar-image-overlay
spec:
  serviceAccountName: default-ns-sa
  packageRef:
    refName: deployment-metrics.tanzu.vmware
    versionSelection:
      constraints: 1.0.0
      prereleases: {}
  values:
  - secretRef:
      name: metrics-values
---
apiVersion: v1
kind: Secret
metadata:
  name: jaegar-image-overlay
  namespace: tkg-system
stringData:
  add-ns-label.yml: |
    #@ load("@ytt:data", "data")
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"Jaeger"}),expects="1+"
    ---
    spec:
      #@overlay/match missing_ok=True
      allInOne:
        #@overlay/match missing_ok=True
        image: #@ data.values.jaegar_image
---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-values
  namespace: tkg-system
stringData:
  values.yml: |
    ---
    jaegar_image: harbor.build.h2o-2-18171.h2o.vmware.com/library/metrics@sha256:d42e451d73188d1d47c60dff6cf645b73b7cc470a6463fcae03aa7dfb9ab8b59