---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata: 
  name: deployment-metrics-package-repo
spec:
  fetch:
    imgpkgBundle:
      image: harbor.build.h2o-2-18171.h2o.vmware.com/metrics/deployment-metrics-package-repo:1.0.0
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: deployment-metrics-install
spec:
  serviceAccountName: default
  packageRef:
    refName: deployment-metrics.tanzu.vmware
    versionSelection:
      constraints: 1.0.0
